// SPDX-License-Identifier: AGPL-3.0-only

//! tarpc server implementation for `LoamSpine`.
//!
//! High-performance binary RPC for primal-to-primal communication.
//! Uses pure Rust tarpc - no protobuf, no gRPC, no C++ tooling.

#![allow(clippy::wildcard_imports)]

use crate::error::ApiError;
use crate::rpc::LoamSpineRpc;
use crate::service::LoamSpineRpcService;
use crate::types::*;
use futures::prelude::*;
use std::net::SocketAddr;
use std::sync::Arc;
use tarpc::server::incoming::Incoming;
use tarpc::server::{self, Channel};
use tarpc::tokio_serde::formats::Json;
use tracing::{info, warn};

/// tarpc server for `LoamSpine`.
///
/// Implements the `LoamSpineRpc` trait generated by the tarpc macro.
#[derive(Clone)]
pub struct LoamSpineTarpcServer {
    service: Arc<LoamSpineRpcService>,
}

impl LoamSpineTarpcServer {
    /// Create a new tarpc server.
    #[must_use]
    pub fn new(service: LoamSpineRpcService) -> Self {
        Self {
            service: Arc::new(service),
        }
    }

    /// Create with default service.
    #[must_use]
    pub fn default_server() -> Self {
        Self::new(LoamSpineRpcService::default_service())
    }
}

// Implement the tarpc service trait
impl LoamSpineRpc for LoamSpineTarpcServer {
    async fn create_spine(
        self,
        _: tarpc::context::Context,
        request: CreateSpineRequest,
    ) -> Result<CreateSpineResponse, ApiError> {
        self.service.create_spine(request).await
    }

    async fn get_spine(
        self,
        _: tarpc::context::Context,
        request: GetSpineRequest,
    ) -> Result<GetSpineResponse, ApiError> {
        self.service.get_spine(request).await
    }

    async fn seal_spine(
        self,
        _: tarpc::context::Context,
        request: SealSpineRequest,
    ) -> Result<SealSpineResponse, ApiError> {
        self.service.seal_spine(request).await
    }

    async fn append_entry(
        self,
        _: tarpc::context::Context,
        request: AppendEntryRequest,
    ) -> Result<AppendEntryResponse, ApiError> {
        self.service.append_entry(request).await
    }

    async fn get_entry(
        self,
        _: tarpc::context::Context,
        request: GetEntryRequest,
    ) -> Result<GetEntryResponse, ApiError> {
        self.service.get_entry(request).await
    }

    async fn get_tip(
        self,
        _: tarpc::context::Context,
        request: GetTipRequest,
    ) -> Result<GetTipResponse, ApiError> {
        self.service.get_tip(request).await
    }

    async fn mint_certificate(
        self,
        _: tarpc::context::Context,
        request: MintCertificateRequest,
    ) -> Result<MintCertificateResponse, ApiError> {
        self.service.mint_certificate(request).await
    }

    async fn transfer_certificate(
        self,
        _: tarpc::context::Context,
        request: TransferCertificateRequest,
    ) -> Result<TransferCertificateResponse, ApiError> {
        self.service.transfer_certificate(request).await
    }

    async fn loan_certificate(
        self,
        _: tarpc::context::Context,
        request: LoanCertificateRequest,
    ) -> Result<LoanCertificateResponse, ApiError> {
        self.service.loan_certificate(request).await
    }

    async fn return_certificate(
        self,
        _: tarpc::context::Context,
        request: ReturnCertificateRequest,
    ) -> Result<ReturnCertificateResponse, ApiError> {
        self.service.return_certificate(request).await
    }

    async fn get_certificate(
        self,
        _: tarpc::context::Context,
        request: GetCertificateRequest,
    ) -> Result<GetCertificateResponse, ApiError> {
        self.service.get_certificate(request).await
    }

    async fn anchor_slice(
        self,
        _: tarpc::context::Context,
        request: AnchorSliceRequest,
    ) -> Result<AnchorSliceResponse, ApiError> {
        self.service.anchor_slice(request).await
    }

    async fn checkout_slice(
        self,
        _: tarpc::context::Context,
        request: CheckoutSliceRequest,
    ) -> Result<CheckoutSliceResponse, ApiError> {
        self.service.checkout_slice(request).await
    }

    async fn generate_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: GenerateInclusionProofRequest,
    ) -> Result<GenerateInclusionProofResponse, ApiError> {
        self.service.generate_inclusion_proof(request).await
    }

    async fn verify_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: VerifyInclusionProofRequest,
    ) -> Result<VerifyInclusionProofResponse, ApiError> {
        self.service.verify_inclusion_proof(request).await
    }

    async fn health_check(
        self,
        _: tarpc::context::Context,
        request: HealthCheckRequest,
    ) -> Result<HealthCheckResponse, ApiError> {
        self.service.health_check(request).await
    }

    async fn commit_session(
        self,
        _: tarpc::context::Context,
        request: CommitSessionRequest,
    ) -> Result<CommitSessionResponse, ApiError> {
        self.service.commit_session(request).await
    }

    async fn commit_braid(
        self,
        _: tarpc::context::Context,
        request: CommitBraidRequest,
    ) -> Result<CommitBraidResponse, ApiError> {
        self.service.commit_braid(request).await
    }
}

/// Run the tarpc server on the specified address.
///
/// # Errors
///
/// Returns error if server fails to bind or run.
pub async fn run_tarpc_server(
    addr: SocketAddr,
    service: LoamSpineRpcService,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let listener = tarpc::serde_transport::tcp::listen(&addr, Json::default).await?;
    let server = LoamSpineTarpcServer::new(service);

    info!("🚀 LoamSpine tarpc server listening on {}", addr);

    listener
        .filter_map(|r| async {
            match r {
                Ok(transport) => Some(transport),
                Err(e) => {
                    warn!("Failed to accept connection: {}", e);
                    None
                }
            }
        })
        .map(server::BaseChannel::with_defaults)
        // Limit connections per IP
        .max_channels_per_key(10, |t| {
            t.transport().peer_addr().map_or_else(
                |_| std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED),
                |a| a.ip(),
            )
        })
        .map(|channel| {
            let server = server.clone();
            channel.execute(server.serve())
        })
        // Flatten the nested streams into one stream of futures
        .flatten()
        // Process up to 100 concurrent request futures
        .buffer_unordered(100)
        .for_each(|()| async {})
        .await;

    Ok(())
}

#[cfg(test)]
#[path = "tarpc_server_tests.rs"]
mod tests;
