// SPDX-License-Identifier: AGPL-3.0-or-later

//! tarpc server implementation for `LoamSpine`.
//!
//! High-performance structured RPC for primal-to-primal communication.
//! Uses pure Rust tarpc with JSON serde transport over TCP — no protobuf,
//! no gRPC, no C++ tooling. The transport is JSON-over-TCP (not a compact
//! binary codec); this provides interoperability with non-Rust consumers
//! while keeping the tarpc service contract type-safe at compile time.

#![allow(
    clippy::wildcard_imports,
    reason = "tarpc service macro requires wildcard imports from crate::types::*; allow not expect: unfulfilled in test target"
)]

use crate::error::{ApiError, ServerError};
use crate::rpc::LoamSpineRpc;
use crate::service::LoamSpineRpcService;
use crate::types::*;
use futures::prelude::*;
use std::net::SocketAddr;
use std::sync::Arc;
use tarpc::server::incoming::Incoming;
use tarpc::server::{self, Channel};
use tarpc::tokio_serde::formats::Json;
use tracing::{info, warn};

/// Default maximum concurrent request futures processed in parallel.
pub const DEFAULT_MAX_CONCURRENT_REQUESTS: usize = 100;

/// Default maximum active channels (connections) per unique client IP.
pub const DEFAULT_MAX_CHANNELS_PER_IP: u32 = 10;

/// Configuration for the tarpc server.
#[derive(Clone, Debug)]
pub struct TarpcServerConfig {
    /// Maximum concurrent request futures processed in parallel.
    pub max_concurrent_requests: usize,
    /// Maximum active channels (connections) per unique client IP.
    pub max_channels_per_ip: u32,
}

impl Default for TarpcServerConfig {
    fn default() -> Self {
        Self {
            max_concurrent_requests: DEFAULT_MAX_CONCURRENT_REQUESTS,
            max_channels_per_ip: DEFAULT_MAX_CHANNELS_PER_IP,
        }
    }
}

/// tarpc server for `LoamSpine`.
///
/// Implements the `LoamSpineRpc` trait generated by the tarpc macro.
#[derive(Clone)]
pub struct LoamSpineTarpcServer {
    service: Arc<LoamSpineRpcService>,
}

impl LoamSpineTarpcServer {
    /// Create a new tarpc server.
    #[must_use]
    pub fn new(service: LoamSpineRpcService) -> Self {
        Self {
            service: Arc::new(service),
        }
    }

    /// Create with default service.
    #[must_use]
    pub fn default_server() -> Self {
        Self::new(LoamSpineRpcService::default_service())
    }
}

// Implement the tarpc service trait
impl LoamSpineRpc for LoamSpineTarpcServer {
    async fn create_spine(
        self,
        _: tarpc::context::Context,
        request: CreateSpineRequest,
    ) -> Result<CreateSpineResponse, ApiError> {
        self.service.create_spine(request).await
    }

    async fn get_spine(
        self,
        _: tarpc::context::Context,
        request: GetSpineRequest,
    ) -> Result<GetSpineResponse, ApiError> {
        self.service.get_spine(request).await
    }

    async fn list_spines(
        self,
        _: tarpc::context::Context,
        request: ListSpinesRequest,
    ) -> Result<ListSpinesResponse, ApiError> {
        self.service.list_spines(request).await
    }

    async fn spine_status(
        self,
        _: tarpc::context::Context,
        request: SpineStatusRequest,
    ) -> Result<SpineStatusResponse, ApiError> {
        self.service.spine_status(request).await
    }

    async fn seal_spine(
        self,
        _: tarpc::context::Context,
        request: SealSpineRequest,
    ) -> Result<SealSpineResponse, ApiError> {
        self.service.seal_spine(request).await
    }

    async fn append_entry(
        self,
        _: tarpc::context::Context,
        request: AppendEntryRequest,
    ) -> Result<AppendEntryResponse, ApiError> {
        self.service.append_entry(request).await
    }

    async fn append_entry_batch(
        self,
        _: tarpc::context::Context,
        request: AppendEntryBatchRequest,
    ) -> Result<AppendEntryBatchResponse, ApiError> {
        self.service.append_entry_batch(request).await
    }

    async fn get_entry(
        self,
        _: tarpc::context::Context,
        request: GetEntryRequest,
    ) -> Result<GetEntryResponse, ApiError> {
        self.service.get_entry(request).await
    }

    async fn get_tip(
        self,
        _: tarpc::context::Context,
        request: GetTipRequest,
    ) -> Result<GetTipResponse, ApiError> {
        self.service.get_tip(request).await
    }

    async fn list_entries(
        self,
        _: tarpc::context::Context,
        request: ListEntriesRequest,
    ) -> Result<ListEntriesResponse, ApiError> {
        self.service.list_entries(request).await
    }

    async fn mint_certificate(
        self,
        _: tarpc::context::Context,
        request: MintCertificateRequest,
    ) -> Result<MintCertificateResponse, ApiError> {
        self.service.mint_certificate(request).await
    }

    async fn transfer_certificate(
        self,
        _: tarpc::context::Context,
        request: TransferCertificateRequest,
    ) -> Result<TransferCertificateResponse, ApiError> {
        self.service.transfer_certificate(request).await
    }

    async fn loan_certificate(
        self,
        _: tarpc::context::Context,
        request: LoanCertificateRequest,
    ) -> Result<LoanCertificateResponse, ApiError> {
        self.service.loan_certificate(request).await
    }

    async fn return_certificate(
        self,
        _: tarpc::context::Context,
        request: ReturnCertificateRequest,
    ) -> Result<ReturnCertificateResponse, ApiError> {
        self.service.return_certificate(request).await
    }

    async fn mint_certificate_batch(
        self,
        _: tarpc::context::Context,
        request: MintCertificateBatchRequest,
    ) -> Result<MintCertificateBatchResponse, ApiError> {
        self.service.mint_certificate_batch(request).await
    }

    async fn get_certificate(
        self,
        _: tarpc::context::Context,
        request: GetCertificateRequest,
    ) -> Result<GetCertificateResponse, ApiError> {
        self.service.get_certificate(request).await
    }

    async fn verify_certificate(
        self,
        _: tarpc::context::Context,
        request: VerifyCertificateRequest,
    ) -> Result<VerifyCertificateResponse, ApiError> {
        self.service.verify_certificate(request).await
    }

    async fn certificate_lifecycle(
        self,
        _: tarpc::context::Context,
        request: CertificateLifecycleRequest,
    ) -> Result<CertificateLifecycleResponse, ApiError> {
        self.service.certificate_lifecycle(request).await
    }

    async fn certificate_history(
        self,
        _: tarpc::context::Context,
        request: CertificateHistoryRequest,
    ) -> Result<CertificateHistoryResponse, ApiError> {
        self.service.certificate_history(request).await
    }

    async fn publish_anchor(
        self,
        _: tarpc::context::Context,
        request: AnchorPublishRequest,
    ) -> Result<AnchorPublishResponse, ApiError> {
        self.service.publish_anchor(request).await
    }

    async fn publish_anchor_batch(
        self,
        _: tarpc::context::Context,
        request: AnchorPublishBatchRequest,
    ) -> Result<AnchorPublishBatchResponse, ApiError> {
        self.service.publish_anchor_batch(request).await
    }

    async fn verify_anchor(
        self,
        _: tarpc::context::Context,
        request: AnchorVerifyRequest,
    ) -> Result<AnchorVerifyResponse, ApiError> {
        self.service.verify_anchor(request).await
    }

    async fn anchor_slice(
        self,
        _: tarpc::context::Context,
        request: AnchorSliceRequest,
    ) -> Result<AnchorSliceResponse, ApiError> {
        self.service.anchor_slice(request).await
    }

    async fn checkout_slice(
        self,
        _: tarpc::context::Context,
        request: CheckoutSliceRequest,
    ) -> Result<CheckoutSliceResponse, ApiError> {
        self.service.checkout_slice(request).await
    }

    async fn generate_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: GenerateInclusionProofRequest,
    ) -> Result<GenerateInclusionProofResponse, ApiError> {
        self.service.generate_inclusion_proof(request).await
    }

    async fn verify_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: VerifyInclusionProofRequest,
    ) -> Result<VerifyInclusionProofResponse, ApiError> {
        self.service.verify_inclusion_proof(request).await
    }

    async fn health_check(
        self,
        _: tarpc::context::Context,
        request: HealthCheckRequest,
    ) -> Result<HealthCheckResponse, ApiError> {
        self.service.health_check(request).await
    }

    async fn dehydrate_session(
        self,
        _: tarpc::context::Context,
        request: DehydrateSessionRequest,
    ) -> Result<DehydrateSessionResponse, ApiError> {
        self.service.dehydrate_session(request).await
    }

    async fn commit_session(
        self,
        _: tarpc::context::Context,
        request: CommitSessionRequest,
    ) -> Result<CommitSessionResponse, ApiError> {
        self.service.commit_session(request).await
    }

    async fn commit_braid(
        self,
        _: tarpc::context::Context,
        request: CommitBraidRequest,
    ) -> Result<CommitBraidResponse, ApiError> {
        self.service.commit_braid(request).await
    }

    async fn bond_ledger_store(
        self,
        _: tarpc::context::Context,
        request: BondLedgerStoreRequest,
    ) -> Result<BondLedgerStoreResponse, ApiError> {
        self.service.bond_ledger_store(request).await
    }

    async fn bond_ledger_retrieve(
        self,
        _: tarpc::context::Context,
        request: BondLedgerRetrieveRequest,
    ) -> Result<BondLedgerRetrieveResponse, ApiError> {
        self.service.bond_ledger_retrieve(request).await
    }

    async fn bond_ledger_list(
        self,
        _: tarpc::context::Context,
        request: BondLedgerListRequest,
    ) -> Result<BondLedgerListResponse, ApiError> {
        self.service.bond_ledger_list(request).await
    }

    async fn trust_anchor(
        self,
        _: tarpc::context::Context,
        request: TrustAnchorRequest,
    ) -> Result<TrustAnchorResponse, ApiError> {
        self.service.trust_anchor(request).await
    }

    async fn trust_query(
        self,
        _: tarpc::context::Context,
        request: TrustQueryRequest,
    ) -> Result<TrustQueryResponse, ApiError> {
        self.service.trust_query(request).await
    }

    async fn trust_event_count(
        self,
        _: tarpc::context::Context,
        request: TrustEventCountRequest,
    ) -> Result<TrustEventCountResponse, ApiError> {
        self.service.trust_event_count(request).await
    }

    async fn negotiate_btsp(
        self,
        _: tarpc::context::Context,
        request: BtspNegotiateRequest,
    ) -> Result<BtspNegotiateResponse, ApiError> {
        self.service.negotiate_btsp(request).await
    }
}

/// Run the tarpc server on the specified address with default configuration.
///
/// # Errors
///
/// Returns error if server fails to bind or run.
pub async fn run_tarpc_server(
    addr: SocketAddr,
    service: LoamSpineRpcService,
) -> Result<(), ServerError> {
    run_tarpc_server_with_config(addr, service, TarpcServerConfig::default()).await
}

/// Run the tarpc server with explicit configuration.
///
/// # Errors
///
/// Returns error if server fails to bind or run.
pub async fn run_tarpc_server_with_config(
    addr: SocketAddr,
    service: LoamSpineRpcService,
    config: TarpcServerConfig,
) -> Result<(), ServerError> {
    let listener = tarpc::serde_transport::tcp::listen(&addr, Json::default)
        .await
        .map_err(|e| ServerError::Bind {
            context: format!("tarpc TCP listen at {addr}"),
            source: e,
        })?;
    let server = LoamSpineTarpcServer::new(service);

    info!("tarpc server listening on {}", addr);

    listener
        .filter_map(|r| async {
            match r {
                Ok(transport) => Some(transport),
                Err(e) => {
                    warn!("failed to accept connection: {}", e);
                    None
                }
            }
        })
        .map(server::BaseChannel::with_defaults)
        .max_channels_per_key(config.max_channels_per_ip, |t| {
            t.transport().peer_addr().map_or_else(
                |_| std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED),
                |a| a.ip(),
            )
        })
        .map(|channel| {
            let server = server.clone();
            channel.execute(server.serve())
        })
        .flatten()
        .buffer_unordered(config.max_concurrent_requests)
        .for_each(|()| async {})
        .await;

    Ok(())
}

/// Serve the tarpc protocol on an already-connected UDS stream (G65).
///
/// After G65 protocol negotiation selects tarpc, the stream is wrapped in
/// length-delimited + JSON serde framing and served via `BaseChannel`.
/// The caller has already consumed the `PROTOCOLS:` / `PROTOCOL:` lines.
///
/// Uses the same `Json` serde transport as the C2 `run_tarpc_uds_server`
/// for wire compatibility — all tarpc consumers use identical framing.
///
/// # Errors
///
/// Returns `std::io::Error` on transport failures.
#[cfg(unix)]
pub async fn serve_tarpc_connection(
    stream: tokio::net::UnixStream,
    service: LoamSpineRpcService,
) -> std::io::Result<()> {
    let length_delimited = tokio_util::codec::length_delimited::Builder::new().new_framed(stream);
    let transport = tarpc::serde_transport::new(length_delimited, Json::default());
    let server = LoamSpineTarpcServer::new(service);
    Box::pin(
        server::BaseChannel::with_defaults(transport)
            .execute(server.serve())
            .for_each(|resp| async move {
                resp.await;
            }),
    )
    .await;
    Ok(())
}

/// Handle for a tarpc UDS server, managing socket lifecycle.
#[cfg(unix)]
pub struct TarpcUdsHandle {
    shutdown: tokio::sync::watch::Sender<bool>,
    path: std::path::PathBuf,
}

#[cfg(unix)]
impl TarpcUdsHandle {
    /// Signal the tarpc UDS server to stop.
    pub fn stop(&self) {
        let _ = self.shutdown.send(true);
    }

    /// Get the socket path.
    #[must_use]
    pub fn path(&self) -> &std::path::Path {
        &self.path
    }
}

#[cfg(unix)]
impl Drop for TarpcUdsHandle {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.path);
    }
}

/// Run a tarpc server on a Unix domain socket (C2 dual-socket pattern).
///
/// Binds at the given path alongside the JSON-RPC `.sock` listener,
/// providing the high-performance binary framing channel for
/// primal-to-primal composition.
///
/// # Errors
///
/// Returns error if the socket cannot be bound.
#[cfg(unix)]
pub async fn run_tarpc_uds_server(
    path: impl Into<std::path::PathBuf>,
    service: LoamSpineRpcService,
) -> Result<TarpcUdsHandle, ServerError> {
    run_tarpc_uds_server_with_config(path, service, TarpcServerConfig::default()).await
}

/// Run a tarpc UDS server with explicit configuration.
///
/// # Errors
///
/// Returns error if the socket cannot be bound.
#[cfg(unix)]
pub async fn run_tarpc_uds_server_with_config(
    path: impl Into<std::path::PathBuf>,
    service: LoamSpineRpcService,
    config: TarpcServerConfig,
) -> Result<TarpcUdsHandle, ServerError> {
    let path = path.into();

    if let Some(parent) = path.parent() {
        let parent = parent.to_owned();
        tokio::task::spawn_blocking(move || std::fs::create_dir_all(parent))
            .await
            .map_err(|e| ServerError::Bind {
                context: format!("spawn_blocking join: {e}"),
                source: std::io::Error::other(e.to_string()),
            })?
            .map_err(|e| ServerError::Bind {
                context: format!("create dir for tarpc UDS at {}", path.display()),
                source: e,
            })?;
    }

    let path_rm = path.clone();
    tokio::task::spawn_blocking(move || {
        let _ = std::fs::remove_file(&path_rm);
    })
    .await
    .map_err(|e| ServerError::Bind {
        context: format!("cleanup stale tarpc socket: {e}"),
        source: std::io::Error::other(e.to_string()),
    })?;

    let listener = tarpc::serde_transport::unix::listen(&path, Json::default)
        .await
        .map_err(|e| ServerError::Bind {
            context: format!("tarpc UDS listen at {}", path.display()),
            source: e,
        })?;
    let server = LoamSpineTarpcServer::new(service);

    info!("tarpc UDS server listening on {}", path.display());

    let (shutdown_tx, mut shutdown_rx) = tokio::sync::watch::channel(false);
    let serve_path = path.clone();

    tokio::spawn(async move {
        let accept_loop = listener
            .filter_map(|r| async {
                match r {
                    Ok(transport) => Some(transport),
                    Err(e) => {
                        warn!("tarpc UDS accept error: {e}");
                        None
                    }
                }
            })
            .map(server::BaseChannel::with_defaults)
            .map(|channel| {
                let server = server.clone();
                channel.execute(server.serve())
            })
            .flatten()
            .buffer_unordered(config.max_concurrent_requests)
            .for_each(|()| async {});

        tokio::select! {
            () = accept_loop => {
                info!("tarpc UDS server on {} completed", serve_path.display());
            }
            _ = shutdown_rx.changed() => {
                info!("tarpc UDS server on {} shutting down", serve_path.display());
            }
        }
    });

    Ok(TarpcUdsHandle {
        shutdown: shutdown_tx,
        path,
    })
}

#[cfg(test)]
#[path = "tarpc_server_tests.rs"]
mod tests;
