// SPDX-License-Identifier: AGPL-3.0-only

//! tarpc server implementation for `LoamSpine`.
//!
//! High-performance binary RPC for primal-to-primal communication.
//! Uses pure Rust tarpc - no protobuf, no gRPC, no C++ tooling.

#![allow(clippy::wildcard_imports)]

use crate::error::ApiError;
use crate::rpc::LoamSpineRpc;
use crate::service::LoamSpineRpcService;
use crate::types::*;
use futures::prelude::*;
use std::net::SocketAddr;
use std::sync::Arc;
use tarpc::server::incoming::Incoming;
use tarpc::server::{self, Channel};
use tarpc::tokio_serde::formats::Json;
use tracing::{info, warn};

/// tarpc server for `LoamSpine`.
///
/// Implements the `LoamSpineRpc` trait generated by the tarpc macro.
#[derive(Clone)]
pub struct LoamSpineTarpcServer {
    service: Arc<LoamSpineRpcService>,
}

impl LoamSpineTarpcServer {
    /// Create a new tarpc server.
    #[must_use]
    pub fn new(service: LoamSpineRpcService) -> Self {
        Self {
            service: Arc::new(service),
        }
    }

    /// Create with default service.
    #[must_use]
    pub fn default_server() -> Self {
        Self::new(LoamSpineRpcService::default_service())
    }
}

// Implement the tarpc service trait
impl LoamSpineRpc for LoamSpineTarpcServer {
    async fn create_spine(
        self,
        _: tarpc::context::Context,
        request: CreateSpineRequest,
    ) -> Result<CreateSpineResponse, ApiError> {
        self.service.create_spine(request).await
    }

    async fn get_spine(
        self,
        _: tarpc::context::Context,
        request: GetSpineRequest,
    ) -> Result<GetSpineResponse, ApiError> {
        self.service.get_spine(request).await
    }

    async fn seal_spine(
        self,
        _: tarpc::context::Context,
        request: SealSpineRequest,
    ) -> Result<SealSpineResponse, ApiError> {
        self.service.seal_spine(request).await
    }

    async fn append_entry(
        self,
        _: tarpc::context::Context,
        request: AppendEntryRequest,
    ) -> Result<AppendEntryResponse, ApiError> {
        self.service.append_entry(request).await
    }

    async fn get_entry(
        self,
        _: tarpc::context::Context,
        request: GetEntryRequest,
    ) -> Result<GetEntryResponse, ApiError> {
        self.service.get_entry(request).await
    }

    async fn get_tip(
        self,
        _: tarpc::context::Context,
        request: GetTipRequest,
    ) -> Result<GetTipResponse, ApiError> {
        self.service.get_tip(request).await
    }

    async fn mint_certificate(
        self,
        _: tarpc::context::Context,
        request: MintCertificateRequest,
    ) -> Result<MintCertificateResponse, ApiError> {
        self.service.mint_certificate(request).await
    }

    async fn transfer_certificate(
        self,
        _: tarpc::context::Context,
        request: TransferCertificateRequest,
    ) -> Result<TransferCertificateResponse, ApiError> {
        self.service.transfer_certificate(request).await
    }

    async fn loan_certificate(
        self,
        _: tarpc::context::Context,
        request: LoanCertificateRequest,
    ) -> Result<LoanCertificateResponse, ApiError> {
        self.service.loan_certificate(request).await
    }

    async fn return_certificate(
        self,
        _: tarpc::context::Context,
        request: ReturnCertificateRequest,
    ) -> Result<ReturnCertificateResponse, ApiError> {
        self.service.return_certificate(request).await
    }

    async fn get_certificate(
        self,
        _: tarpc::context::Context,
        request: GetCertificateRequest,
    ) -> Result<GetCertificateResponse, ApiError> {
        self.service.get_certificate(request).await
    }

    async fn anchor_slice(
        self,
        _: tarpc::context::Context,
        request: AnchorSliceRequest,
    ) -> Result<AnchorSliceResponse, ApiError> {
        self.service.anchor_slice(request).await
    }

    async fn checkout_slice(
        self,
        _: tarpc::context::Context,
        request: CheckoutSliceRequest,
    ) -> Result<CheckoutSliceResponse, ApiError> {
        self.service.checkout_slice(request).await
    }

    async fn generate_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: GenerateInclusionProofRequest,
    ) -> Result<GenerateInclusionProofResponse, ApiError> {
        self.service.generate_inclusion_proof(request).await
    }

    async fn verify_inclusion_proof(
        self,
        _: tarpc::context::Context,
        request: VerifyInclusionProofRequest,
    ) -> Result<VerifyInclusionProofResponse, ApiError> {
        self.service.verify_inclusion_proof(request).await
    }

    async fn health_check(
        self,
        _: tarpc::context::Context,
        request: HealthCheckRequest,
    ) -> Result<HealthCheckResponse, ApiError> {
        self.service.health_check(request).await
    }

    async fn commit_session(
        self,
        _: tarpc::context::Context,
        request: CommitSessionRequest,
    ) -> Result<CommitSessionResponse, ApiError> {
        self.service.commit_session(request).await
    }

    async fn commit_braid(
        self,
        _: tarpc::context::Context,
        request: CommitBraidRequest,
    ) -> Result<CommitBraidResponse, ApiError> {
        self.service.commit_braid(request).await
    }
}

/// Run the tarpc server on the specified address.
///
/// # Errors
///
/// Returns error if server fails to bind or run.
pub async fn run_tarpc_server(
    addr: SocketAddr,
    service: LoamSpineRpcService,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let listener = tarpc::serde_transport::tcp::listen(&addr, Json::default).await?;
    let server = LoamSpineTarpcServer::new(service);

    info!("🚀 LoamSpine tarpc server listening on {}", addr);

    listener
        .filter_map(|r| async {
            match r {
                Ok(transport) => Some(transport),
                Err(e) => {
                    warn!("Failed to accept connection: {}", e);
                    None
                }
            }
        })
        .map(server::BaseChannel::with_defaults)
        // Limit connections per IP
        .max_channels_per_key(10, |t| {
            t.transport().peer_addr().map_or_else(
                |_| std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED),
                |a| a.ip(),
            )
        })
        .map(|channel| {
            let server = server.clone();
            channel.execute(server.serve())
        })
        // Flatten the nested streams into one stream of futures
        .flatten()
        // Process up to 100 concurrent request futures
        .buffer_unordered(100)
        .for_each(|()| async {})
        .await;

    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    #[test]
    fn test_server_creation() {
        let _server = LoamSpineTarpcServer::default_server();
    }

    #[test]
    fn test_server_with_service() {
        let service = LoamSpineRpcService::default_service();
        let server = LoamSpineTarpcServer::new(service);
        // Verify server is created with service
        assert!(Arc::strong_count(&server.service) >= 1);
    }

    #[test]
    #[allow(clippy::redundant_clone)]
    fn test_server_clone() {
        let server = LoamSpineTarpcServer::default_server();
        let cloned = server.clone();

        // Both should point to the same service (testing Clone impl)
        assert!(Arc::ptr_eq(&server.service, &cloned.service));
    }

    #[tokio::test]
    async fn test_tarpc_health_check() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let request = HealthCheckRequest {
            include_details: false,
        };

        let result = LoamSpineRpc::health_check(server, ctx, request).await;
        assert!(result.is_ok());

        let response = result.unwrap_or_else(|_| panic!("unexpected error"));
        assert!(response.status.is_healthy());
    }

    #[tokio::test]
    async fn test_tarpc_create_spine() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let request = CreateSpineRequest {
            owner: Did::new("did:key:z6MkTest"),
            name: "Test Spine".to_string(),
            config: None,
        };

        let result = LoamSpineRpc::create_spine(server, ctx, request).await;
        assert!(result.is_ok());

        let response = result.unwrap_or_else(|_| panic!("unexpected error"));
        assert!(!response.spine_id.is_nil());
    }

    #[tokio::test]
    async fn test_tarpc_get_nonexistent_spine() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let request = GetSpineRequest {
            spine_id: uuid::Uuid::nil(),
        };

        let result = LoamSpineRpc::get_spine(server, ctx, request).await;
        assert!(result.is_ok());

        let response = result.unwrap_or_else(|_| panic!("unexpected error"));
        assert!(response.spine.is_none());
    }

    #[tokio::test]
    async fn test_tarpc_seal_spine() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        // First create a spine
        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        // Then seal it
        let seal_request = SealSpineRequest {
            spine_id: create_response.spine_id,
            sealer: owner,
        };

        let result = LoamSpineRpc::seal_spine(server, ctx, seal_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_append_entry() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        // Create spine first
        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Entry Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        // Append entry
        let append_request = AppendEntryRequest {
            spine_id: create_response.spine_id,
            entry_type: EntryType::DataAnchor {
                data_hash: [0u8; 32],
                mime_type: Some("text/plain".to_string()),
                size: 100,
            },
            committer: owner,
            payload: None,
        };

        let result = LoamSpineRpc::append_entry(server, ctx, append_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_mint_certificate() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        // Create spine first
        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Cert Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        // Mint certificate
        let mint_request = MintCertificateRequest {
            spine_id: create_response.spine_id,
            cert_type: CertificateType::DigitalGame {
                platform: "steam".to_string(),
                game_id: "hl3".to_string(),
                edition: None,
            },
            owner,
            metadata: None,
        };

        let result = LoamSpineRpc::mint_certificate(server, ctx, mint_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_commit_session() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        // Create spine first
        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Session Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        // Commit session
        let commit_request = CommitSessionRequest {
            spine_id: create_response.spine_id,
            committer: owner,
            session_id: uuid::Uuid::now_v7(),
            session_hash: [0u8; 32],
            vertex_count: 42,
        };

        let result = LoamSpineRpc::commit_session(server, ctx, commit_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_commit_braid() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        // Create spine first
        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Braid Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        // Commit braid
        let braid_request = CommitBraidRequest {
            spine_id: create_response.spine_id,
            committer: owner,
            braid_id: uuid::Uuid::now_v7(),
            braid_hash: [2u8; 32],
            subjects: vec![],
        };

        let result = LoamSpineRpc::commit_braid(server, ctx, braid_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_get_entry() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Entry Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        let append_request = AppendEntryRequest {
            spine_id: create_response.spine_id,
            entry_type: EntryType::DataAnchor {
                data_hash: [1u8; 32],
                mime_type: Some("text/plain".to_string()),
                size: 50,
            },
            committer: owner.clone(),
            payload: None,
        };
        let append_response = LoamSpineRpc::append_entry(server.clone(), ctx, append_request)
            .await
            .unwrap_or_else(|_| panic!("append failed"));

        let get_request = GetEntryRequest {
            spine_id: create_response.spine_id,
            entry_hash: append_response.entry_hash,
        };
        let result = LoamSpineRpc::get_entry(server.clone(), ctx, get_request).await;
        assert!(result.is_ok());
        let response = result.unwrap_or_else(|_| panic!("get_entry failed"));
        assert!(response.found);

        let get_nonexistent = GetEntryRequest {
            spine_id: create_response.spine_id,
            entry_hash: [99u8; 32],
        };
        let result = LoamSpineRpc::get_entry(server, ctx, get_nonexistent).await;
        assert!(result.is_ok());
        let response = result.unwrap_or_else(|_| panic!("get_entry failed"));
        assert!(!response.found);
    }

    #[tokio::test]
    async fn test_tarpc_get_tip() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Tip Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        let get_tip_request = GetTipRequest {
            spine_id: create_response.spine_id,
        };
        let result = LoamSpineRpc::get_tip(server, ctx, get_tip_request).await;
        assert!(result.is_ok());
        let response = result.unwrap_or_else(|_| panic!("get_tip failed"));
        assert!(!response.tip_hash.iter().all(|&b| b == 0));
    }

    #[tokio::test]
    async fn test_tarpc_transfer_certificate() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");
        let new_owner = Did::new("did:key:z6MkNewOwner");

        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Transfer Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        let mint_request = MintCertificateRequest {
            spine_id: create_response.spine_id,
            cert_type: CertificateType::DigitalGame {
                platform: "steam".to_string(),
                game_id: "hl3".to_string(),
                edition: None,
            },
            owner: owner.clone(),
            metadata: None,
        };
        let mint_response = LoamSpineRpc::mint_certificate(server.clone(), ctx, mint_request)
            .await
            .unwrap_or_else(|_| panic!("mint failed"));

        let transfer_request = TransferCertificateRequest {
            certificate_id: mint_response.certificate_id,
            from: owner,
            to: new_owner,
        };
        let result = LoamSpineRpc::transfer_certificate(server, ctx, transfer_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_loan_and_return_certificate() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");
        let borrower = Did::new("did:key:z6MkBorrower");

        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Loan Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        let mint_request = MintCertificateRequest {
            spine_id: create_response.spine_id,
            cert_type: CertificateType::DigitalGame {
                platform: "steam".to_string(),
                game_id: "hl3".to_string(),
                edition: None,
            },
            owner: owner.clone(),
            metadata: None,
        };
        let mint_response = LoamSpineRpc::mint_certificate(server.clone(), ctx, mint_request)
            .await
            .unwrap_or_else(|_| panic!("mint failed"));

        let loan_request = LoanCertificateRequest {
            certificate_id: mint_response.certificate_id,
            lender: owner.clone(),
            borrower: borrower.clone(),
            terms: loam_spine_core::LoanTerms::new().with_duration(3600),
        };
        let result = LoamSpineRpc::loan_certificate(server.clone(), ctx, loan_request).await;
        assert!(result.is_ok());

        let return_request = ReturnCertificateRequest {
            certificate_id: mint_response.certificate_id,
            returner: borrower,
        };
        let result = LoamSpineRpc::return_certificate(server, ctx, return_request).await;
        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_tarpc_anchor_slice() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        let waypoint_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Waypoint".to_string(),
            config: None,
        };
        let waypoint_response = LoamSpineRpc::create_spine(server.clone(), ctx, waypoint_request)
            .await
            .unwrap_or_else(|_| panic!("create waypoint failed"));

        let origin_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Origin".to_string(),
            config: None,
        };
        let origin_response = LoamSpineRpc::create_spine(server.clone(), ctx, origin_request)
            .await
            .unwrap_or_else(|_| panic!("create origin failed"));

        let anchor_request = AnchorSliceRequest {
            waypoint_spine_id: waypoint_response.spine_id,
            slice_id: uuid::Uuid::now_v7(),
            origin_spine_id: origin_response.spine_id,
            committer: owner,
        };
        let result = LoamSpineRpc::anchor_slice(server, ctx, anchor_request).await;
        assert!(result.is_ok());
        let response = result.unwrap_or_else(|_| panic!("anchor failed"));
        assert!(!response.anchor_hash.iter().all(|&b| b == 0));
    }

    #[tokio::test]
    async fn test_tarpc_checkout_slice_nonexistent() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        let waypoint_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Waypoint Checkout".to_string(),
            config: None,
        };
        let waypoint_response = LoamSpineRpc::create_spine(server.clone(), ctx, waypoint_request)
            .await
            .unwrap_or_else(|_| panic!("create waypoint failed"));

        let checkout_request = CheckoutSliceRequest {
            waypoint_spine_id: waypoint_response.spine_id,
            slice_id: uuid::Uuid::now_v7(),
            requester: owner,
        };
        let result = LoamSpineRpc::checkout_slice(server, ctx, checkout_request).await;
        assert!(result.is_err(), "checkout of nonexistent slice should fail");
    }

    #[tokio::test]
    async fn test_tarpc_generate_and_verify_inclusion_proof() {
        let server = LoamSpineTarpcServer::default_server();
        let ctx = tarpc::context::current();
        let owner = Did::new("did:key:z6MkTest");

        let create_request = CreateSpineRequest {
            owner: owner.clone(),
            name: "Proof Test".to_string(),
            config: None,
        };
        let create_response = LoamSpineRpc::create_spine(server.clone(), ctx, create_request)
            .await
            .unwrap_or_else(|_| panic!("create failed"));

        let append_request = AppendEntryRequest {
            spine_id: create_response.spine_id,
            entry_type: EntryType::DataAnchor {
                data_hash: [5u8; 32],
                mime_type: Some("text/plain".to_string()),
                size: 10,
            },
            committer: owner.clone(),
            payload: None,
        };
        let append_response = LoamSpineRpc::append_entry(server.clone(), ctx, append_request)
            .await
            .unwrap_or_else(|_| panic!("append failed"));

        let gen_request = GenerateInclusionProofRequest {
            spine_id: create_response.spine_id,
            entry_hash: append_response.entry_hash,
        };
        let gen_result = LoamSpineRpc::generate_inclusion_proof(server.clone(), ctx, gen_request)
            .await
            .unwrap_or_else(|_| panic!("generate proof failed"));

        let verify_request = VerifyInclusionProofRequest {
            proof: gen_result.proof,
        };
        let result = LoamSpineRpc::verify_inclusion_proof(server, ctx, verify_request).await;
        assert!(result.is_ok());
        let response = result.unwrap_or_else(|_| panic!("verify failed"));
        assert!(response.valid);
    }
}
